ci:
  assert:
    assertions:
      categories:accessibility: [error, minScore: 0.94]
      categories:best-practices: [error, minScore: 1]
      categories:performance: [error, minScore: 0.68]
      categories:seo: [error, minScore: 0.92]
    includePassedAssertions: true
  collect:
    numberOfRuns: 1
    startServerCommand: npx local-web-server --static.maxage 31536000 -p 8080 -d dist-ssr
    startServerReadyPattern: Listening on
    url:
      - http://localhost:8080/en/career-8942b689824112e6
  upload:
    outputDir: .lighthouseci/results
    target: filesystem
